2020-06-28 22:22:29,844 ERROR: Exception on / [GET] [in /Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/justinlabrash/Documents/flask_project/flask_app/routes.py", line 32, in index
    return render_template('index.html', title='Home',  form = form, posts=posts.items, next_url = next_url, prev_url = prev_url)
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/justinlabrash/Documents/flask_project/flask_app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/Users/justinlabrash/Documents/flask_project/flask_app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/justinlabrash/Documents/flask_project/flask_app/templates/base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "/Users/justinlabrash/Documents/flask_project/flask_app/templates/index.html", line 11, in block "app_content"
    {% include '_post.html' %}
  File "/Users/justinlabrash/Documents/flask_project/flask_app/templates/_post.html", line 9, in top-level template code
    said {{ moment(post.timestamp).fromNow() }}:
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask_moment.py", line 156, in fromNow
    return self._render("fromNow", no_suffix=int(no_suffix),
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask_moment.py", line 139, in _render
    t = self._timestamp_as_iso_8601(self.timestamp)
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask_moment.py", line 135, in _timestamp_as_iso_8601
    return timestamp.strftime('%Y-%m-%dT%H:%M:%S' + tz)
jinja2.exceptions.UndefinedError: 'flask_app.models.Post object' has no attribute 'timestamp'
2020-06-28 22:22:44,309 ERROR: Exception on / [GET] [in /Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/justinlabrash/Documents/flask_project/flask_app/routes.py", line 32, in index
    return render_template('index.html', title='Home',  form = form, posts=posts.items, next_url = next_url, prev_url = prev_url)
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/justinlabrash/Documents/flask_project/flask_app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/Users/justinlabrash/Documents/flask_project/flask_app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/justinlabrash/Documents/flask_project/flask_app/templates/base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "/Users/justinlabrash/Documents/flask_project/flask_app/templates/index.html", line 11, in block "app_content"
    {% include '_post.html' %}
  File "/Users/justinlabrash/Documents/flask_project/flask_app/templates/_post.html", line 9, in top-level template code
    said {{ moment(post.created_at).fromNow() }}:
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask_moment.py", line 156, in fromNow
    return self._render("fromNow", no_suffix=int(no_suffix),
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask_moment.py", line 139, in _render
    t = self._timestamp_as_iso_8601(self.timestamp)
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask_moment.py", line 135, in _timestamp_as_iso_8601
    return timestamp.strftime('%Y-%m-%dT%H:%M:%S' + tz)
jinja2.exceptions.UndefinedError: 'flask_app.models.Post object' has no attribute 'timestamp'
2020-06-28 22:23:31,978 INFO: Microblog startup [in /Users/justinlabrash/Documents/flask_project/flask_app/__init__.py:46]
2020-06-28 22:35:00,312 INFO: Microblog startup [in /Users/justinlabrash/Documents/flask_project/flask_app/__init__.py:46]
2020-06-28 22:36:11,840 INFO: Microblog startup [in /Users/justinlabrash/Documents/flask_project/flask_app/__init__.py:46]
2020-06-28 22:36:43,942 INFO: Microblog startup [in /Users/justinlabrash/Documents/flask_project/flask_app/__init__.py:46]
2020-06-28 23:48:26,695 INFO: Microblog startup [in /Users/justinlabrash/Documents/flask_project/flask_app/__init__.py:46]
2020-07-03 11:20:33,675 INFO: Microblog startup [in /Users/justinlabrash/Documents/flask_project/flask_app/__init__.py:75]
2020-07-03 11:20:40,768 INFO: Microblog startup [in /Users/justinlabrash/Documents/flask_project/flask_app/__init__.py:75]
